# Generated by Django 4.1.3 on 2022-11-30 14:22

import django.core.validators
from django.db import migrations, models
import magazinslunce.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='product_pictures', validators=[magazinslunce.common.validators.validate_file_size])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
