# Generated by Django 4.1.3 on 2022-12-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('type',)},
        ),
    ]
